Add MM1 continuum parameters, modify lines parameters for MM2 and MM3
ALMA-IMF/reduction pull request #144
Opened 2021-05-03 20:47 UTC by nonyt

Changes on scripts other imaging_parameters should be ignored
Some line (CO, SiO) parameters (deconvolver) were used in older versions, need to be check and removed

2021-05-03 21:32 UTC, keflavich requested changes
Could you add the CRTF files, and remove the changes to continuum_imaging_selfcal?

2021-05-03 21:32 UTC, keflavich commented on reduction/continuum_imaging_selfcal.py
> +    for robust in (0, 2):
```suggestion
    for robust in (0, -2, 2, -1, 1, -0.5, 0.5):
```

2021-05-03 21:32 UTC, keflavich commented on reduction/imaging_parameters.py
> +            "final": "W43-MM1_B6_final_12M.crtf",
add these CRTF files too

2021-05-03 21:32 UTC, keflavich commented on reduction/masking_script_casa5.py
> +mask_threshold = 3.0 # In mJy sigma_sio_MM2=2.5 12co_MM2=1.5
are these changes intentional?  if so, we can keep them

2021-05-04 00:49 UTC, nonyt commented
I added the masks and restored 2 scripts to the original states. Is it fine now or should I do another pull request?

2021-05-06 12:00 UTC, merged